create table if not exists public.daily_quotes (
  id bigint generated by default as identity primary key,
  quote text not null,
  author text,
  source text,
  language text not null default 'zh',
  tags text[] not null default '{}'::text[],
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_quotes_quote_not_blank
    check (length(trim(quote)) > 0),
  constraint daily_quotes_language_not_blank
    check (length(trim(language)) > 0)
);

create index if not exists daily_quotes_published_idx
  on public.daily_quotes (is_published, id);

create index if not exists daily_quotes_language_idx
  on public.daily_quotes (language);

alter table public.daily_quotes enable row level security;

drop policy if exists "Allow public read published daily quotes" on public.daily_quotes;
create policy "Allow public read published daily quotes"
on public.daily_quotes
for select
to anon
using (is_published = true);
